CREATE TABLE IF NOT EXISTS Event (id INT AUTO_INCREMENT  PRIMARY KEY,  ver_name VARCHAR(250) NOT NULL,  place VARCHAR(250) NOT NULL,  datum VARCHAR(250) NOT NULL,  eventType VARCHAR(250) NOT NULL,  rank VARCHAR(250) NOT NULL,  weather VARCHAR(250) NOT NULL,  description VARCHAR(250) DEFAULT NULL);
CREATE TABLE IF NOT EXISTS EventType (ver_name VARCHAR(250) PRIMARY KEY);
